### PR TITLE
Dependencies updated, output dir cleanup fixed, tests fixed, system t…

### PR DESCRIPTION
**Pull request by remorhaz**
…ests added

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Hi @baev,
Could you add a tag for the new version that contains these changes?
We can't update some other dependencies because this package contains required to an older version of allure-framework/allure-php-api.

**Comment by ihor-sviziev** [comment]
Hi @baev,
Could you add a tag to the latest commit? We really need to update allure-framework/allure-php-api in order to have php8 compatibility, but we can't due to dependencies conflict

**Comment by baev** [comment]
@ihor-sviziev done

**Comment by ihor-sviziev** [comment]
@baev thank you so much!

**Pull request merged**
