### PR TITLE
Added processing of PHPUnit warnings as failures

### PR DESCRIPTION
**Pull request by slavvka**
Added processing of PHPUnit warnings as failures since PHPUnit returns exit code 1 on warnings

Look at https://github.com/allure-framework/allure-phpunit/issues/47

### CODE REVIEW

**Comment by slavvka** [comment]
@baev Could you please review the PR?

**Comment by eduard-sukharev** [comment]
Looks fine, but wouldn't it be better to have this as optional behavior?

**Comment by slavvka** [comment]
> Looks fine, but wouldn't it be better to have this as optional behavior?

Why? PHPUnit unconditionally returns exit code 1 on warnings. That means any CICD system using it will fail. With current behavior it'll fail without any records in an Allure report. Could you please give some use cases?

**Comment by ihor-sviziev** [comment]
@eduard-sukharev any updates on this?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@baev, could you take a look at this PR? I think we should accept it.
To provide more context - Magento 2 using allure for generating reports and publishing the only allure reports. However, sometimes we're getting failing build, but in published reports, no info at all.

**Review by remorhaz — APPROVED** [review]
Well, Allure doesn't have "warning" test status anyway, and it's much better to process "warning" as "failure" than to ignore it.

**Comment by baev** [comment]
looks good, @slavvka could you please rebase and I'll merge

**Comment by slavvka** [comment]
@baev will do

**Review by baev — APPROVED** [review]

**Pull request merged**
